### ISSUE TITLE
Incorrect reporting of applications that launch correctly.

### ISSUE THREAD

**Issue by ethancox127** [killuhwhale/appium#6]
When applications launch and initially prompt the user to accept permissions the applications is reported as "Failed to Open".  There may be other instances where this occurs and they should be added here.

**Comment by ethancox127** [comment]
On ARC-R Helios Hay Day was reported as failing to open and the app window is still showing a black screen where content should be loaded.  Same issue with failing to open Clash of Clans and Brawl Stars.

**Comment by ethancox127** [comment]
This also occurred when prompted to select a Google account after launching the app and being prompted to accept a software agreement.

**Comment by killuhwhale** [comment]
This might be due to the simple "Current act" check which would report a different package name than what we are looking for.

We will most likely need to add a few checks to prevent this, nice catch!

**Comment by killuhwhale** [comment]
For Hay Day it appeared that the Double Click technique being used was clicking on the image on the install page. It wasn't actually installed. Now it installs and detects a Process Died error (newly added due to this app)

Note: All super cells games are crashing and are detected with Process Died error check (Clash of Clans and Brawl Stars tested too).

Lets keep an eye out for other apps failing for permission pop ups and other pop ups.

**Comment by killuhwhale** [comment]
com.adsk.sketchbook  Autodesk SketchBook - Software Agreement issue

**Comment by killuhwhale** [comment]
Now that we are opening app and detecting if the app is open and not just checking if the app is currently in the foreground, we are no longer facing issues where we report that the app didnt launch, when in fact, it did. 

This should fix all pop up issues and misreporting the app status.
